---
- name: "Bootstrap machine"
  hosts: localhost

  vars:
    xdg_config_dir: "~/.config"
  
  roles:
    - role: "nvim/nvim-config"
    - role: "tmux/tmux-config"
    - role: "git/git-config"
    - role: "wezterm/wezterm-config"

